# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('HostID', models.AutoField(primary_key=True, serialize=False)),
                ('HostIP', models.CharField(max_length=64)),
                ('HostName', models.CharField(max_length=128)),
                ('HostMem', models.IntegerField()),
                ('Room', models.CharField(max_length=64)),
                ('Used', models.BooleanField()),
                ('Description', models.CharField(max_length=1024)),
            ],
        ),
    ]
