# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodisInfo',
            fields=[
                ('CodisID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=128)),
                ('Dashboard', models.CharField(max_length=128)),
                ('Description', models.CharField(max_length=1024)),
            ],
        ),
    ]
