# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codisapp', '0002_codisinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='Used',
            field=models.IntegerField(),
        ),
    ]
