# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codisapp', '0003_auto_20160608_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPrefix',
            fields=[
                ('PrefixID', models.AutoField(primary_key=True, serialize=False)),
                ('PrefixName', models.CharField(max_length=128)),
                ('PrefixProject', models.CharField(max_length=128)),
                ('OpOwner', models.CharField(max_length=128)),
                ('RdOwner', models.CharField(max_length=128)),
                ('AccessTime', models.CharField(max_length=128)),
                ('Description', models.CharField(max_length=1024)),
            ],
        ),
    ]
