#!/usr/bin/env python

import os
import sys
import commands

CommandList=[
            'set testkey 123',
            'DECR testkey',
            'DECRBY testkey 10',
            'get testkey',
            'exists testkey',
            'append testkey2 "hello"',
            'STRLEN testkey2',
            'SETRANGE testkey2 6 "world"',
            'SETNX testkey2 "hello"',
            'SETEX testkey3 60 "TTL_60"',
            'SETBIT testkey 100 1',
            'GETBIT testkey 100',
            'BITCOUNT testkey',
            'BITFIELD testkey4 INCRBY i8 100 1 GET u4 0',
            'BITOP AND bit-result testkey testkey4',
            'PSETEX testkey5 10000 "TTL_milliseconds_10000"',
            'MSET testkey6 "6" testkey7 "7" testkey8 "8"',
            'MSETNX testkey6 "5" testkey7 "5" testkey8 "8"',
            'INCR testkey6',
            'INCRBY testkey7 2',
            'INCRBYFLOAT testkey8 0.8',
            'GETSET testkey 1',
            'GETRANGE testkey2 -5 -1',
            'MGET testkey testkey2 testkey3 testkey4 testkey5 testkey6 testkey7 testkey8',
            'keys *key*',
            'HSET hkey1 k1 "hello"',
            'HSET hkey2 k1 "10" k2 "20" k3 "30"',
            'HSETNX hkey1 k1 "world"',
            'HVALS hkey2',
            'HSCAN hkey2 0',
            'HSTRLEN hkey1 k1',
            'HLEN hkey2',
            'HKEYS hkey2',
            'HGET hkey1 k1',
            'HINCRBY hkey2 k1 -9',
            'HEXISTS hkey2 k4',
            'HINCRBYFLOAT hkey2 k4 4.4',
            'HGETALL hkey2',
            'HDEL hkey2 k1 k2',
            'HMGET hkey2 k3 k4',
            'LPUSH lkey1 hello',
            'LPUSHX lkey1 hi',
            'RPUSH lkey1 world a b c d e',
            'RPUSHX lkey2 world',
            'RPOP lkey1',
            'RPOPLPUSH lkey1 lkey2',
            'LTRTM lkey1 1 -1',
            'LSET lkey1 1 codis',
            'LLEN lkey1',
            'LINSERT lkey1 AFTER "a" "codis"',
            'BRPOPLPUSH lkey1 lkey2 5',
            'LRANGE lkey2 0 -1',
            'LINDEX lkey1 0',
            'BLPOP lkey1 0',
            'BRPOP lkey1 lkey2 0',
            'LREM lkey1 0 codis',
            'LPOP lkey1',
            'SADD skey1 "a" "b" "c" "d" "e"',
            'SADD skey2 "e" "f" "g" "h"'
            'SCARD skey1',
            'SMEMBERS skey1',
            'SISMEMBER skey1 "a"',
            'SMOVE skey1 skey2 "a"',
            'SPOP skey1',
            'SREM skey1 d e',
            'SRANDMEMBER skey1 3',
            'SDIFF skey1 skey2',
            'SDIFFSTORE skey3 skey1 skey2',
            'SINTER skey1 skey2',
            'SINTERSTORE skey4 skey1 skey2',
            'SUNION skey1 skey2',
            'SUNION skey5 skey1 skey2',
            'SSCAN skey5 0',
            'ZADD zkey1 70 a 80 b 85 c 90 d 92 e 98 f',
            'ZCARD zkey1',
            'ZCOUNT zkey1 80 90',
            'ZINCRBY zkey1 10 b',
            'ZRANGE zkey1 0 -1 WITHSCORES',
            'ZRANGEBYSCORE zkey1 -inf 90 WITHSCORES',
            'ZRANK zkey1 b',
            'ZREM zkey1 b',
            'ZREMRANGEBYRANK zkey1 0 1',
            'ZREMRANGBYSCORE zkey1 95 100',
            'ZREVRANGE zkey1 0 -1 WITHSCORES',
            'ZREVRANGEBYSCORE zkey1 100 -inf WITHSCORES',
            'ZREVRANK zkey1 d',
            'ZSCORE zkey1 e',
            'ZUNIONSTORE zkey2 1 zkey1 WEIGHTS 2',
            'ZINTERSTORE zkey3 2 zkey1 zkey2',
            'ZSCAN zkey1 0',
            'ZRANGEBYLEX zkey1 [a (e',
            'ZLEXCOUNT zkey1 - +',
            'ZREMRANGEBYLEX zkey1 [c [e',
            'DEL zkey3',
            'DUMP zkey1',
            'EXISTS zkey1',
            'EXPIRE zkey2 10',
            'EXPIREAT zkey2 2355292000',
            'KEYS *key*',
            'MIGRATE 100.0.0.4 7000 zkey1 0 1000',
            'MOVE zkey2 1',
            'OBJECT IDLETIME zkey2',
            'PERSIST zkey2',
            'PEXPIRE zkey2 10000',
            'PEXPIREAT zkey2 100000000000',
            'PTTL zkey2',
            'RANDOMKEY',
            'RENAME zkey2 k',
            'RENAME k k2',
            'RESTORE k 0 "\\x00\\x01v\\a\\x00n:\\x1bA\\x11\\xf2_\\xd4" REPLACE',
            'SORT skey1 ALPHA',
            'TTL skey1',
            'TYPE skey1',
            'SCAN 0',
            'BGREWRITEAOF',
            'BGSAVE',
            'CLIENT SETNAME test',
            'CLIENT GETNAME',
            'CLIENT LIST',
            'CLIENT KILL 127.0.0.1:8888',
            'CONFIG SET maxmemory 21474836480',
            'CONFIG GET maxmemory',
            'CONFIG RESETSTAT',
            'CONFIG REWRITE',
            'DBSIZE',
            'DEBUG OBJECT k',
            'INFO KEYSPACE',
            'LASTSAVE',
            'SAVE',
            'SLOWLOG GET',
            'TIME',
            'FLUSHALL',
            'SHUTDOWN'
             ]

if len(sys.argv) != 3:
  print '''Usage:
    python CodisProxyCommandTest.py ProxyIP PorxyPort'''
  exit()

for cmd in CommandList:
  print "________" + cmd + "________"
  command = "echo '" + cmd +"'|./redis-cli -h " + sys.argv[1] +" -p " + sys.argv[2]
  status, output = commands.getstatusoutput(command)
  #print status
  print "ret='" + output + "'"

